### PR TITLE
Cache collections

### PR DESCRIPTION
**Pull request by justinlittman**
## Why was this change made? 🤔
To reduce the load on DSA with redundant calls.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test) that exercise indexing*** (e.g. searches in Argo for newly created/updated items, access_indexing_spec) and/or test in [stage|qa] environment, in addition to specs. ⚡

Unit

### CODE REVIEW

**Comment by edsu** [comment]
So this cache will live as long as the process lives?

**Comment by justinlittman** [comment]
@edsu Yes. That seems safe enough. If it proves problematic, we can come up with a more sophisticated strategy.

**Comment by edsu** [comment]
I guess I just worry about how we will notice that it's become problematic.

**Review by edsu — APPROVED** [review]
I'm approving this, but w/ reservations because I'm worried that implementing caching this way could lead to bugs that are difficult to diagnose. I also think that maybe we should think about putting a caching layer in front of DSA. But I realize these aren't practical things to consider while things are on fire.

**Review by ndushay — APPROVED** [review]
approving but would like another reviewer as I am also listening to standup

**Comment by justinlittman** [comment]
For what it is worth, we do this sort of caching for APOs in other parts of the code.

**Comment by edsu** [comment]
Do APOs change at roughly the same rate as Collections?

**Pull request merged**
