### PR TITLE
Revert changes to ETD handling

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?

When we changed etds to use the ETD_INDEXER, we lost workflows and datastream displays.
This reverts those commits so we treat ETDs as Dor::Item and removes the unused ETD_INDEXER since it was never used.

## Was the documentation (README, DevOpsDocs, wiki, consul, etc.) updated?

n/a

## Does this change affect how this application integrates with other services?

no.
If so, please confirm change was tested on stage and/or test added to sul-dlss/infrastructure-integration-test.

### CODE REVIEW

**Comment by justinlittman** [comment]
So there are no ETD unique properties that need to be indexed?

**Comment by jcoyne** [comment]
@justinlittman I don't believe so.

**Comment by peetucket** [comment]
Wasn't there some issue about the associated APO not being indexed for ETDs that this change was originally attended to address?

**Comment by jcoyne** [comment]
@ndushay the shas that were reverted are in the commit messages.

**Comment by peetucket** [comment]
looks fine

**Pull request merged**
