### PR TITLE
Add simplecov to get percentage coverage report on laptop runs

### PR DESCRIPTION
**Pull request by jmartin-sul**

### CODE REVIEW

**Comment by jmartin-sul** [comment]
not actually showing percentage covered (in PR or on laptop).  odd.  will investigate...

**Comment by drh-stanford** [comment]
is this PR still being worked on? if not, shall we delete the branch?

**Comment by jmartin-sul** [comment]
i don't think it's being worked on actively, though it is still something i'd like to add.  i'd prefer to leave the branch and PR in limbo until we can come back around to it, since the branch list for this project isn't that cluttered, though i also wouldn't be too torn up if it were deleted.

**Comment by cbeer** [comment]
I've rebased this and got it working.

**Pull request merged**
