### PR TITLE
add is_it_working gem

### PR DESCRIPTION
**Pull request by jmartin-sul**
added it.  it appears to be working.

@eefahy

### CODE REVIEW

**Comment by jkeck** [comment]
But what checks if `is_it_working` is working?  

whoa

**Comment by eefahy** [comment]
that's a big whoa

**Comment by tonynavarrete** [comment]
Isn’t it checks all the way down?

tony

==================================================
Tony Navarrete
Associate Director for Product & Service Management
Digital Library Systems and Services, Stanford University Libraries
650.724.1809   tonyn@stanford.edu<mailto:tonyn@stanford.edu>

On Feb 19, 2016, at 5:08 PM, Erin Fahy <notifications@github.com<mailto:notifications@github.com>> wrote:


that's a big whoa

**Comment by jmartin-sul** [comment]
the `meta_is_it_working` team ran into trouble trying to figure out how to test when `meta_is_it_working` is working.

**Pull request merged**
